import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  kk: {
    services: 'Қызметтер',
    myBookings: 'Менің броньдарым',
    admin: 'Админ',
    login: 'Кіру',
    logout: 'Шығу',
    register: 'Тіркелу',
    heroTitle: 'Бізбен бірге тиімді, әрі тез саяхаттаңыз!',
    heroSubtitle: 'Келесі кездесуді оңай брондаңыз. Бастау үшін төмендегі қызметтің бірін таңдаңыз.',
    searchPlaceholder: 'Іздеу...',
    sortBy: 'Сұрыптау',
    minPrice: 'Мин. баға',
    maxPrice: 'Макс. баға',
    minRating: 'Мин. рейтинг',
    viewDetails: 'Толығырақ',
    duration: 'Ұзақтығы',
    days: 'күн',
    price: 'Бағасы',
    rating: 'Рейтинг',
    location: 'Орналасқан жері',
    findOnMap: 'Картадан табу',
    save: 'Сақтау',
    edit: 'Өңдеу',
    delete: 'Жою',
    addService: 'Қызмет қосу',
    bookingSuccess: 'Брондау сәтті аяқталды!',
    payment: 'Төлем',
    welcome: 'Қош келдіңіз',
    actions: 'Әрекеттер',
    title: 'Атауы',
    shortDescription: 'Қысқаша сипаттама',
    description: 'Сипаттама',
    images: 'Суреттер',
    chooseFiles: 'Файлдарды таңдаңыз',
    selected: 'Таңдалды',
    cancel: 'Болдырмау',
    loading: 'Жүктелуде...',
    existingServices: 'Бар қызметтер',
    saveChanges: 'Өзгерістерді сақтау',
    noImage: 'Сурет жоқ',
    map: 'Карта',
    category: 'Категория',
    allCategories: 'Барлық категориялар',
    selectCategory: 'Категорияны таңдаңыз',
    allRightsReserved: 'Барлық құқықтар қорғалған',
    cars: 'Машиналар',
    special_tech: 'Арнайы техника',
    housing: 'Тұрғын үй',
    events: 'Іс-шаралар',
    appName: 'Booking System',
    footerDescription: 'Бізбен бірге тиімді, әрі тез саяхаттаңыз!',
    quickLinks: 'Жылдам сілтемелер',
    contactUs: 'Кері байланыс',
    email: 'Email',
    password: 'Құпия сөз',
    loginSubtitle: 'Жеке кабинетке кіру үшін почта және құпия сөз енгізіңіз.',
    registerSubtitle: 'Жаңа аккаунт ашу үшін форманы толтырыңыз.',
    alreadyHaveAccount: 'Аккаунтыңыз бар ма?',
    newToSite: 'Жаңа қолданушысыз?',
    nameLabel: 'Аты-жөні?',
    pleaseWait: 'Күте тұрыңыз...',
    confirmCancel: 'Брондауды жоюға сенімдісіз бе?',
    cancelBooking: 'Брондауды жою',
    completePayment: 'Төлемді аяқтау',
    noBookingsYet: 'Сізде әлі брондаулар жоқ. Қызметті брондау үшін басты бетке өтіңіз!',
    errorLoadingBookings: 'Брондауларды жүктеу мүмкін болмады.',
    statusPaid: 'Төленді',
    statusPending: 'Күтілуде',
    statusCancelled: 'Жойылды',
    bookingFor: 'брондау',
    selectTime: 'Уақытты таңдаңыз',
    proceedToPayment: 'Төлемге өту',
    paymentSuccess: 'Төлем сәтті өтті!',
    payNow: 'Қазір төлеу',
    processing: 'Өңделуде...',
    redirecting: 'Жөндеу жүріп жатыр...',
    bookingNotFound: 'Брондау табылмады.',
    advantages: 'Артықшылықтары',
    bookNow: 'Брондау',
    time: 'Уақыт',
    confirmDelete: 'Бұл қызметті жоюға сенімдісіз бе?',
    serviceAdded: 'Қызмет сәтті қосылды!',
    serviceUpdated: 'Қызмет сәтті жаңартылды!',
    errorSavingService: 'Қызметті сақтау кезінде қате кетті.',
    addressNotFound: 'Мекен-жай картадан табылмады.',
    errorFindingAddress: 'Мекен-жайды іздеу кезінде қате кетті.',
    maxImagesError: 'Максимум 5 сурет қосуға болады.',
    invalidFileTypeError: 'Тек суреттерді (JPG, PNG, WEBP) жүктеуге болады.',
    selectedLocation: 'Таңдалған орын',
    fieldsRequired: 'Барлық өрістерді толтыру қажет.',
    loginFailed: 'Кіру сәтсіз аяқталды.',
    registerFailed: 'Тіркелу сәтсіз аяқталды.',
    noServicesFound: 'Қазіргі уақытта қызметтер жоқ.',
    errorLoadingService: 'Қызметті жүктеу сәтсіз аяқталды.',
    addAdvantage: 'Артықшылық қосу',
    advantagePlaceholder: 'Артықшылықты енгізіңіз (мысалы: Тегін Wi-Fi)',
    'Name, email, and password are required.': 'Аты, электрондық поштасы және құпия сөз міндетті.',
    'This email is already registered.': 'Бұл электрондық пошта тіркеліп қойған.',
    'Server error during registration.': 'Тіркелу кезіндегі сервер қатесі.',
    'Email and password are required.': 'Электрондық пошта және құпия сөз міндетті.',
    'Invalid email or password.': 'Электрондық пошта немесе құпия сөз қате.',
    'Server error during login.': 'Кіру кезіндегі сервер қатесі.',
    'Auth required.': 'Авторизация қажет.',
    'service_id and booking_date are required.': 'service_id және booking_date міндетті өрістер.',
    'Slot is already booked. Please choose another time or service.': 'Бұл уақыт бос емес. Басқа уақытты немесе қызметті таңдаңыз.',
    'Failed to create booking.': 'Брондау сәтсіз аяқталды.',
    'User ID is required.': 'Қолданушы ID міндетті.',
    'Server error fetching user bookings': 'Брондауларды алу кезіндегі сервер қатесі.',
    'Booking not found': 'Брондау табылмады.',
    'Server error fetching booking': 'Брондауды алу кезіндегі сервер қатесі.',
    'User must be logged in to cancel a booking.': 'Брондауды жою үшін жүйеге кіру қажет.',
    'Booking not found or not authorized.': 'Брондау табылмады немесе рұқсат жоқ.',
    'Booking already cancelled.': 'Брондау қазірдің өзінде жойылған.',
    'Internal server error while cancelling booking.': 'Брондауды жою кезіндегі сервер қатесі.',
    'Payment processing failed. Please try again.': 'Төлемді өңдеу сәтсіз аяқталды. Қайта көріңіз.',
    'Authorization token is required.': 'Авторизация токені қажет.',
    'Invalid or expired authorization token.': 'Авторизация токені қате немесе мерзімі біткен.',
    'Admin access required.': 'Админ рұқсаты қажет.',
    'Server error fetching services': 'Қызметтерді алу кезінде қате кетті.',
    'Service not found': 'Қызмет табылмады.',
    'Server error fetching service': 'Қызметті алу кезінде қате кетті.',
  },
  ru: {
    services: 'Услуги',
    myBookings: 'Мои бронирования',
    admin: 'Админ',
    login: 'Войти',
    logout: 'Выйти',
    register: 'Регистрация',
    heroTitle: 'Путешествуйте выгодно и быстро вместе с нами!',
    heroSubtitle: 'Забронируйте следующую встречу легко. Выберите одну из услуг ниже, чтобы начать.',
    searchPlaceholder: 'Поиск...',
    sortBy: 'Сортировка',
    minPrice: 'Мин. цена',
    maxPrice: 'Макс. цена',
    minRating: 'Мин. рейтинг',
    viewDetails: 'Подробнее',
    duration: 'Длительность',
    days: 'дн.',
    price: 'Цена',
    rating: 'Рейтинг',
    location: 'Местоположение',
    findOnMap: 'Найти на карте',
    save: 'Сохранить',
    edit: 'Редактировать',
    delete: 'Удалить',
    addService: 'Добавить услугу',
    bookingSuccess: 'Бронирование успешно!',
    payment: 'Оплата',
    welcome: 'Добро пожаловать',
    actions: 'Действия',
    title: 'Название',
    shortDescription: 'Краткое описание',
    description: 'Описание',
    images: 'Изображения',
    chooseFiles: 'Выбрать файлы',
    selected: 'Выбрано',
    cancel: 'Отмена',
    loading: 'Загрузка...',
    existingServices: 'Существующие услуги',
    saveChanges: 'Сохранить изменения',
    noImage: 'Нет фото',
    map: 'Карта',
    category: 'Категория',
    allCategories: 'Все категории',
    selectCategory: 'Выберите категорию',
    allRightsReserved: 'Все права защищены',
    cars: 'Машины',
    special_tech: 'Спецтехника',
    housing: 'Жилье',
    events: 'Мероприятия',
    appName: 'Booking System',
    footerDescription: 'Ваш надежный партнер для бронирования различных услуг.',
    quickLinks: 'Быстрые ссылки',
    contactUs: 'Свяжитесь с нами',
    email: 'Email',
    password: 'Пароль',
    loginSubtitle: 'Введите почту и пароль для входа в личный кабинет.',
    registerSubtitle: 'Заполните форму для создания нового аккаунта.',
    alreadyHaveAccount: 'Уже есть аккаунт?',
    newToSite: 'Новый пользователь?',
    nameLabel: 'Ваше имя',
    pleaseWait: 'Пожалуйста, подождите...',
    confirmCancel: 'Вы уверены, что хотите отменить бронирование?',
    cancelBooking: 'Отменить бронирование',
    completePayment: 'Завершить оплату',
    noBookingsYet: 'У вас пока нет бронирований. Перейдите на главную страницу, чтобы забронировать услугу!',
    errorLoadingBookings: 'Не удалось загрузить ваши бронирования.',
    statusPaid: 'Оплачено',
    statusPending: 'В ожидании',
    statusCancelled: 'Отменено',
    bookingFor: 'бронирование',
    selectTime: 'Выберите время',
    proceedToPayment: 'Перейти к оплате',
    paymentSuccess: 'Оплата прошла успешно!',
    payNow: 'Оплатить сейчас',
    processing: 'Обработка...',
    redirecting: 'Перенаправление...',
    bookingNotFound: 'Бронирование не найдено.',
    advantages: 'Преимущества',
    bookNow: 'Забронировать',
    time: 'Время',
    confirmDelete: 'Удалить этот сервис?',
    serviceAdded: 'Услуга успешно добавлена!',
    serviceUpdated: 'Услуга успешно обновлена!',
    errorSavingService: 'Ошибка при сохранении услуги.',
    addressNotFound: 'Адрес не найден на карте.',
    errorFindingAddress: 'Ошибка при поиске адреса.',
    maxImagesError: 'Максимум 5 изображений на сервис.',
    invalidFileTypeError: 'Допускаются только изображения (JPG, PNG, WEBP).',
    selectedLocation: 'Выбранное местоположение',
    fieldsRequired: 'Поля должны быть заполнены.',
    loginFailed: 'Ошибка входа.',
    registerFailed: 'Ошибка регистрации.',
    noServicesFound: 'Услуг пока нет.',
    errorLoadingService: 'Ошибка загрузки услуги.',
    addAdvantage: 'Добавить преимущество',
    advantagePlaceholder: 'Введите преимущество (например: Бесплатный Wi-Fi)',
    'Name, email, and password are required.': 'Имя, email и пароль обязательны.',
    'This email is already registered.': 'Этот email уже зарегистрирован.',
    'Server error during registration.': 'Ошибка сервера при регистрации.',
    'Email and password are required.': 'Email и пароль обязательны.',
    'Invalid email or password.': 'Неверный email или пароль.',
    'Server error during login.': 'Ошибка сервера при входе.',
    'Auth required.': 'Требуется авторизация.',
    'service_id and booking_date are required.': 'service_id и booking_date обязательны.',
    'Slot is already booked. Please choose another time or service.': 'Это время уже занято. Пожалуйста, выберите другое время или услугу.',
    'Failed to create booking.': 'Не удалось создать бронирование.',
    'User ID is required.': 'ID пользователя обязателен.',
    'Server error fetching user bookings': 'Ошибка сервера при получении бронирований.',
    'Booking not found': 'Бронирование не найдено.',
    'Server error fetching booking': 'Ошибка сервера при получении бронирования.',
    'User must be logged in to cancel a booking.': 'Для отмены бронирования необходимо войти в систему.',
    'Booking not found or not authorized.': 'Бронирование не найдено или нет прав.',
    'Booking already cancelled.': 'Бронирование уже отменено.',
    'Internal server error while cancelling booking.': 'Внутренняя ошибка сервера при отмене бронирования.',
    'Payment processing failed. Please try again.': 'Ошибка при обработке платежа. Попробуйте еще раз.',
    'Authorization token is required.': 'Требуется токен авторизации.',
    'Invalid or expired authorization token.': 'Недействительный или просроченный токен.',
    'Admin access required.': 'Требуются права администратора.',
    'Server error fetching services': 'Ошибка сервера при получении услуг.',
    'Service not found': 'Услуга не найдена.',
    'Server error fetching service': 'Ошибка сервера при получении услуги.',
  },
  en: {
    services: 'Services',
    myBookings: 'My Bookings',
    admin: 'Admin',
    login: 'Login',
    logout: 'Logout',
    register: 'Register',
    heroTitle: 'Travel efficiently and quickly with us!',
    heroSubtitle: 'Book your next meeting easily. Choose one of the services below to get started.',
    searchPlaceholder: 'Search...',
    sortBy: 'Sort By',
    minPrice: 'Min Price',
    maxPrice: 'Max Price',
    minRating: 'Min Rating',
    viewDetails: 'View Details',
    duration: 'Duration',
    days: 'days',
    price: 'Price',
    rating: 'Rating',
    location: 'Location',
    findOnMap: 'Find on Map',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    addService: 'Add Service',
    bookingSuccess: 'Booking Successful!',
    payment: 'Payment',
    welcome: 'Welcome',
    actions: 'Actions',
    title: 'Title',
    shortDescription: 'Short Description',
    description: 'Description',
    images: 'Images',
    chooseFiles: 'Choose Files',
    selected: 'Selected',
    cancel: 'Cancel',
    loading: 'Loading...',
    existingServices: 'Existing Services',
    saveChanges: 'Save Changes',
    noImage: 'No Image',
    map: 'Map',
    category: 'Category',
    allCategories: 'All Categories',
    selectCategory: 'Select a category',
    allRightsReserved: 'All rights reserved',
    cars: 'Cars',
    special_tech: 'Special Equipment',
    housing: 'Housing',
    events: 'Events',
    appName: 'Booking System',
    footerDescription: 'Travel efficiently and quickly with us!',
    quickLinks: 'Quick Links',
    contactUs: 'Contact Us',
    email: 'Email',
    password: 'Password',
    loginSubtitle: 'Enter your email and password to log in.',
    registerSubtitle: 'Fill out the form to create a new account.',
    alreadyHaveAccount: 'Already have an account?',
    newToSite: 'New user?',
    nameLabel: 'Your Name',
    pleaseWait: 'Please wait...',
    confirmCancel: 'Are you sure you want to cancel this booking?',
    cancelBooking: 'Cancel Booking',
    completePayment: 'Complete Payment',
    noBookingsYet: 'You have no bookings yet. Go to the home page to book a service!',
    errorLoadingBookings: 'Failed to load your bookings.',
    statusPaid: 'Paid',
    statusPending: 'Pending',
    statusCancelled: 'Cancelled',
    bookingFor: 'booking',
    selectTime: 'Select Time',
    proceedToPayment: 'Proceed to Payment',
    paymentSuccess: 'Payment Successful!',
    payNow: 'Pay Now',
    processing: 'Processing...',
    redirecting: 'Redirecting...',
    bookingNotFound: 'Booking not found.',
    advantages: 'Advantages',
    bookNow: 'Book Now',
    time: 'Time',
    confirmDelete: 'Delete this service?',
    serviceAdded: 'Service added successfully!',
    serviceUpdated: 'Service updated successfully!',
    errorSavingService: 'Error saving service.',
    addressNotFound: 'Address not found on map.',
    errorFindingAddress: 'Error finding address.',
    maxImagesError: 'Maximum 5 images per service.',
    invalidFileTypeError: 'Only images (JPG, PNG, WEBP) are allowed.',
    selectedLocation: 'Selected Location',
    fieldsRequired: 'Fields are required.',
    loginFailed: 'Login failed.',
    registerFailed: 'Registration failed.',
    noServicesFound: 'No services found.',
    errorLoadingService: 'Failed to load service.',
    addAdvantage: 'Add Advantage',
    advantagePlaceholder: 'Enter advantage (e.g., Free Wi-Fi)',
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('language') || 'kk');

  useEffect(() => {
    localStorage.setItem('language', lang);
  }, [lang]);

  const t = (key) => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
